### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by friederbluemle**
Some more dependency updates, and all whitespace errors fixed (separate commit). A few xml files and a jpg file also had their executable bit set, which I removed (separate commit as well).

<sub><sup>Please NO GitHub rebase/squash merges. If you'd like me to combine some or all of the commits, please let me know, and I will update my branch. Thank you.</sup></sub>

### CODE REVIEW

**Comment by davemorrissey** [comment]
When I merged your previous PR and released it as 3.7.0, developers reported problems I could not reproduce, caused by spurious values in the `AttributeSet` passed to the view's constructor on inflate. Rolling back that PR fixed the problem. I don't have a solution so will stick to the older tools and gradle scripts.

**Comment by friederbluemle** [comment]
@davemorrissey Sorry. That's rather odd. Do you happen to have more details about the issues so I can investigate as well?

**Comment by davemorrissey** [comment]
Have a look at the recent bugs raised. Initial indications were that rolling back the build changes fixed the problem, but I'm awaiting more feedback that might suggest my proguard file was the cause. It's not clear whether problems only show up in release builds.

**Comment by friederbluemle** [comment]
Okay, I saw the issues.
Please provide some more info:
1. When did you release 3.7.0
2. Did the issues only start happening recently
3. When you create a release build, or edit the project, how do you do it? Gradle command line, Android Studio, Eclipse (?!) - I noticed most of the project is still in the Eclipse/Ant format.

ProGuard in release builds seems like a possible candidate for the bugs.
I will also do some local tests here.
Thanks!

**Comment by davemorrissey** [comment]
3.7.0 was released a few days ago and immediately caused problems. I don't test release signed builds and will have to set something up to do that. I'm using Android Studio and build releases from the gradle command line.

**Comment by friederbluemle** [comment]
Thanks @davemorrissey - I opened  #355 to discuss further investigation.

**Pull request closed without merging**
