### PR TITLE
Add display region.

### PR DESCRIPTION
**Pull request by t101d**
Set the region to display instead of the whole image.

### CODE REVIEW

**Comment by davemorrissey** [comment]
Thanks! This looks good to me. Unfortunately I can't merge it because I've made a major change to the view on the `preview-image` branch that this can't be merged with. However, what I can do is re-implement your change on my branch. This won't be entirely straightforward because I've merged the two views and added preview functionality, so I may need to implement the region selection for all three methods of displaying an image.

I'm curious what you needed this for and why you aren't displaying the whole image?

**Comment by t101d** [comment]
Thank you for sharing this library. It really helps me a lot.
I'd like to download and display a very large image. The image can be divided into several parts. The whole image or part of it is displayed according to the use cases.

**Comment by davemorrissey** [comment]
Okay, that makes sense. Just so you're aware, it takes longer to initialise the BitmapRegionDecoder for a very large image, so sometimes it's better to work with smaller images. It looks like that doesn't suit what you're doing though. I'll try to get this merged into my changes for the next release as soon as I can.

**Comment by davemorrissey** [comment]
Released in v3.0.0.

**Pull request merged**
