### PR TITLE
Add flipping feature and example

### PR DESCRIPTION
**Pull request by VitalyNikonorov**

### CODE REVIEW

**Comment by davemorrissey** [comment]
I tried this out but unfortunately when I zoom into an image that requires tiling, each individual tile is flipped, but not moved to where it should be considering the whole image should be flipped. Fixing this requires significant changes to the tile map initialisation to take into account which bit of the source image you actually need.

screenshot_20161104-212534

**Comment by VitalyNikonorov** [comment]
Sorry, confused the order of the arguments for prescaling. 
Now it is fixed and I made some changes in card image.
P.S.: before fixing there were no errors in case of both flipping simultaneously

**Comment by davemorrissey** [comment]
I can't test this because it conflicts with recent changes.

Because you're using `Bitmap.createBitmap` to create flipped copies of images, the view will be significantly slower and use more memory, causing more crashes. Tiles need to be flipped using a matrix when they are rendered. Unfortunately I won't be able to merge this PR if it adds calls to `createBitmap`.

**Comment by davemorrissey** [comment]
Closing now because this approach to flipping will make the view use too much memory. Feel free to try it with matrix rotation instead of `createBitmap`.

**Pull request closed without merging**
