### PR TITLE
Implement on zoom change listener

### PR DESCRIPTION
**Pull request by a-kokulyuk**
I've added possibility to add on Zoom change listener

### CODE REVIEW

**Comment by davemorrissey** [comment]
This looks okay but I'm curious what the use case is? I've considered this before but not done it because it would result in thousands of calls to the listener which would slow the view down, and I couldn't think of examples where an Activity or Fragment would need to know this. Normally only a subclass would need to know scale changes, and they can get the current scale when onDraw is called.

Also I think it might be better to receive pan and orientation change events too, with an OnImageViewStateChanged listener and the ImageViewState class.

**Comment by laurencedawson** [comment]
One use case would be hiding chrome as a user zooms in.

**Comment by rossimo** [comment]
It's also useful to know if the user actually zoomed in on the image. Optimizations could be made if the user never zooms in.

**Comment by elfujiyama69** [comment]
Another case could be my case. I have an app with two images overlap, one of them is a metro image and on the top is the is another image with alpha 0 with different colours for each metro station. With this method I will know which metro station that user selected.

For this reason will be awesome that when I zoom the alpha 0 image set the same zoom for the other.

I think that I could do it with the interfaces of onTouch but will be a little for difficult that with a onZoomChanged event.

Even without this. I have to say that this is one of the best android libraries I have found.

Thank you very much for your work!!

PD: Sorry for my poor english :S

**Comment by davemorrissey** [comment]
I've now implemented this feature, but included support for listening to pan changes too. I also wanted to explicitly exclude events prompted by initialisation and calls to public methods, and make it clear where events originated from. This is all in commit cb89069 and will be in the next version. Thanks for the PR - I'll close it as it's been superceded by a different implementation.

**Comment by fukemy** [comment]
Hi. i have some informationView in top of imageView, i want to hide it when start double click or start zoom -> hide informationView, then when imageView scale back to minimum -> show informationView
 Can u give some advices? thanks

**Pull request closed without merging**
