### PR TITLE
fixing double touch on two different images 

### PR DESCRIPTION
**Pull request by filnik**
As https://github.com/davemorrissey/subsampling-scale-image-view/pull/119 but now the feature is disabled only if two images are clicked at the same time (so it should work fine with viewpagers if there is only one image per page).

### CODE REVIEW

**Comment by davemorrissey** [comment]
This problem is caused by a bug in Android triggered by using the support library and the snackbar in your app and by using two views on the page - a very rare combination. The bug isn't caused by this view alone, it's been reported to Google by other developers.

This change carries a risk of breaking view paging if an expected touch event is missed due to the activity ending or a screen orientation change, so I'd rather not merge it. I think the best option for you is to use your own fork or try extending the class to override touch handling.

I will try to reproduce and investigate this problem to see if there's a safer workaround.

**Comment by filnik** [comment]
Actually I have no snackbar. I've not tried, but I think that to reproduce the problem you just have to put two images in the same layout, put one finger to each view and simply move them keeping touching the screen.

The solution I proposed will disable the feature only when you have 2 images touched at the same time. So it will work as it works right now, except when you touch 2 images at once. You will have a bug only if you touch 2 images IN a viewpager with this fix --> almost never and it is safe.

If you don't want to merge it ok, but I think it's pretty safe right now.

**Comment by davemorrissey** [comment]
Ah sorry, it was the Snackbar in some of the other bug reports, but the DrawerLayout in yours. I would like to find a workaround for this problem but I spent a lot of time getting touch handling to work properly for view pagers and I don't want to take any risks to support a rare case like this. I'm not keen on the use of statics for communication between views, not least because it is possible for the ACTION_UP event to be missed, which would corrupt the view until the app is force stopped. I hope there's a better solution, and I'll do some investigation when I can.

**Comment by filnik** [comment]
Ok. I'll let you know if I came up with a better solution then, thanks :)

**Pull request closed without merging**
