### PR TITLE
migrate to androidx lib

### PR DESCRIPTION
**Pull request by vfishv**

### CODE REVIEW

**Comment by davemorrissey** [comment]
I don't develop with Android any more so I don't know much about androidx, but I think if I merged this, every developer using this library would have the androidx library added to their projects. That's assuming androidx can coexist with the support libraries and they aren't forced to upgrade to androidx to use this library.

It seems there might have to be parallel forks - a support library version and an androidx version. But as I don't work on this library any more I don't have the time to build sample apps to test the permutations.

**Comment by perrochon** [comment]
I _think_ I am developing the same with to use AndroidX. If the library doesn't update (which seems justified), should I use this branch instead?

**Comment by madmas** [comment]
AndroidX is the future, please accept this MR and provide a new version @davemorrissey

**Comment by hereisderek** [comment]
for converting dependencies to androidx, google provided a neat gradle flag to do it automatically, however to convert a lib with androidx to using support library there's also a command tool for that (which if I remembered correctly operate on the aar file). 

both the conversion however could have problem since it's kinda direct reference replacement. 

still, it's high time to make the transaction.

**Pull request merged**
