### PR TITLE
Auto zoom

### PR DESCRIPTION
**Pull request by CB-ysx**
Add auto zoom when load image is onReady

### CODE REVIEW

**Comment by davemorrissey** [comment]
Thanks for this. It changes the default behaviour for tall images so they zoom in to the top left after load. Unfortunately there are a few reasons why I won't be able to merge it:

* Changing the default behaviour causes unexpected problems when developers update, and I don't believe the new behaviour is right for most.
* Zooming in to the top left overrides any scale and center the developer has preset.
* Many developers wouldn't want the animation but it isn't configurable.
* The configuration option `setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP)` can be used to avoid black borders, if that was the aim of this PR.

If you can describe what your requirements are, another solution may be possible.

**Comment by CB-ysx** [comment]
Thanks for your reasons!
I realized that changing the default behavior was really bad.

And here is my requirement:
- After load the picture, the view can make the picture full width instead of scaling to show the 
   whole picture.

In fact, I've tried to use the configuration option `setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP)`.It does solve my requirement when load the big picture, but it doesn't solve to the small picture which width smaller than the width of view. And this configuration option causes another question that the small picture can not be scale.

If you have the better solution, please tell me.Thanks!

Finally, my English is not very good, please understand!

**Comment by davemorrissey** [comment]
I didn't design the view with small images in mind so it doesn't handle them well. The default is to show the image centered with black borders on all sides if filling the screen would mean exceeding the maximum scale, giving a highly pixellated image. This is right for some developers, but not everyone so I need to make it more configurable without making it more complicated than it already is!

Here's a workaround you could try. For small images, this adjusts the max scale on load so the image will fill the screen but can't be scaled any further. Use this with `SCALE_TYPE_CENTER_CROP` and I think you'll get the behaviour you described.

    imageView.setOnImageEventListener(new SubsamplingScaleImageView.DefaultOnImageEventListener() {
        @Override
        public void onReady() {
            if (imageView.getMaxScale() < imageView.getMinScale()) {
                imageView.setMaxScale(imageView.getMinScale());
                imageView.resetScaleAndCenter();
            }
        }
    });

**Comment by CB-ysx** [comment]
Sorry! It could not solve my problem, because of the image can't be scaled.I still use my method in my project.Thank you!

**Pull request closed without merging**
